#!/usr/bin/python3.6.3

import sys
import argparse
import socketHandler

def validLength(param):
	if(len(str(param)) <= 4096):
		return True
	else:
		return False

def validPort(PORT):
	if(1024 <= PORT <= 65535):
		return True
	else:
		return False

def main():
	argParser = argparse.ArgumentParser()

	argParser.add_argument("PORT", type = int)
	argParser.add_argument("PASSWORD", nargs = '?', type = str, default = "admin")

	args = argParser.parse_args()

	if(not validLength(args.PORT)):
		print('server: error: argument PORT: length can\'t exceed 4096 digits')
		sys.exit(255)

	if(not validLength(args.PASSWORD)):
		print('server: error: argument PASSWORD: length can\'t exceed 4096 characters')
		sys.exit(255)

	# Check if password contains any quotation marks
	if("\"" in args.PASSWORD):
		print('server: error: argument PASSWORD: password does not need \" (quotes)')
		sys.exit(255)
	
	# Run server if port is valid
	if(validPort(args.PORT)):
		socketHandler.runServer(args.PORT)
	else:
		print('server: error: argument PORT: valid TCP ports are between 1024-65535')
		sys.exit(255)

# Needed to run main()
if __name__ == "__main__":
	main()
